#!/bin/bash
#
# This script creates the complete folder structure for the DITA Toolchain
# project inside the 'Playground' directory.
#

# --- Configuration ---
# We are running this from 'worksamples', so the base dir is 'Playground'
BASE_DIR="Playground"
PROJECT_DIR="${BASE_DIR}/.dita-toolchain"

echo "Ensuring base directory exists: ./${BASE_DIR}"
mkdir -p "${BASE_DIR}"

echo "Setting up the DITA Toolchain skeleton in ./${PROJECT_DIR}..."

# --- 1. Create the Tool Folders ---
echo "Creating tool directories..."
mkdir -p "${PROJECT_DIR}/tools/1_MapArchitect"
mkdir -p "${PROJECT_DIR}/tools/2_ContentGenerator"
mkdir -p "${PROJECT_DIR}/tools/3_PreviewPublisher"

# --- 2. Create the Project Output Folder ---
echo "Creating project directory..."
mkdir -p "${PROJECT_DIR}/projects"

# --- 3. Create Placeholder Files (so Git can track empty dirs) ---
echo "Creating .gitkeep placeholders..."
touch "${PROJECT_DIR}/tools/1_MapArchitect/.gitkeep"
touch "${PROJECT_DIR}/tools/2_ContentGenerator/.gitkeep"
touch "${PROJECT_DIR}/tools/3_PreviewPublisher/.gitkeep"
touch "${PROJECT_DIR}/projects/.gitkeep"

# --- 4. Create a simple README ---
echo "Creating README.md"
cat <<'EOM' > "${PROJECT_DIR}/README.md"
# DITA-First Toolchain

This project contains a suite of tools to brainstorm, author, and publish
DITA-first technical documentation.

## Folders

* `/tools`: Contains the standalone HTML/JS applications for the toolchain.
* `/projects`: Contains the output (guides) generated by these tools.
EOM

echo ""
echo -e "\x1b[32mSkeleton creation complete.\x1b[0m"
echo "You can now add your 'dita_map_generator.html' file to:"
echo "${PROJECT_DIR}/tools/1_MapArchitect/"
echo ""
